// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TryMassTransit.Consumer;

namespace TryMassTransit.Consumer.Migrations
{
    [DbContext(typeof(ReportSagaDbContext))]
    [Migration("20191102091727_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TryMassTransit.Consumer.ReportSagaState", b =>
                {
                    b.Property<Guid>("CorrelationId");

                    b.Property<string>("CurrentState")
                        .HasMaxLength(200);

                    b.Property<string>("EMail")
                        .HasMaxLength(200);

                    b.Property<Guid>("ReportId");

                    b.Property<DateTime>("RequestTime");

                    b.HasKey("CorrelationId");

                    b.ToTable("sagaReportSagaState");
                });
#pragma warning restore 612, 618
        }
    }
}
